### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Khjin06k** [Khjin06k/Section5_Unit2-homework#1]
### 만들고자 하는 기능
1. Todo 생성 기능
2. Todo 진행/No진행 체크 기능
3. Todo 삭제 기능

### 해당 기능을 구현하기 위해 해야 할 일은 무엇인가요?
1. [ ] Todo 생성 기능(CREAT)
2. [ ] Todo 수정 기능(UPDATE)
3. [ ] Todo 읽어오기 기능 (READ)
4. [ ]  Todo 삭제 기능(DELETE)
